[project]
name = "speech"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.4.2",
    "librosa>=0.11.0",
    "matplotlib>=3.10.8",
    "torch>=2.9.1",
]
